### ISSUE TITLE
Open-sourcing the reward models

### ISSUE THREAD

**Issue by Glavin001** [allenai/FineGrainedRLHF#1]
Thank you so much for sharing your work. I've been excited to learn more about your approach, and hopefully contribute, since I first read your paper!

I noticed there are reward models mentioned which I have been unable to find: https://github.com/allenai/FineGrainedRLHF/blob/main/FRL/launch_final.sh#L11-L16

Do you plan to open-source either the models themselves, or how to recreate/train them, or both? Thanks again!

**Comment by ellenmellon** [comment]
Yes we will release the code, data and models for reward models very soon. Thanks for your interest!

**Comment by ellenmellon** [comment]
Please find our reward models, data and training scripts in the current repo!
