### ISSUE TITLE
Weights of reward functions in RLHF

### ISSUE THREAD

**Issue by jsw7460** [allenai/FineGrainedRLHF#10]
In the paper, the default weights for the rewards are (0.3, 0.5, 0.3). The implementation seems to add distinct rewards with uniform weights.

https://github.com/allenai/FineGrainedRLHF/blob/3ce87b80f999f61adfb440df12e14e1771ca4eef/tasks/qa_feedback/training/reward.py#L447C29-L447C29

**Comment by ellenmellon** [comment]
The weights are enforced here:  https://github.com/allenai/FineGrainedRLHF/blob/3ce87b80f999f61adfb440df12e14e1771ca4eef/tasks/qa_feedback/training/train_finegrained.py#L197
