### ISSUE TITLE
Running PPO with a subset of RMs

### ISSUE THREAD

**Issue by vishwa27yvs** [allenai/FineGrainedRLHF#13]
Thank you for the detailed work and open-sourcing your code! It is super helpful

I noticed in the paper you did some ablations (Table 5) on how removing a particular Reward qualitatively changes performance. I wanted to perform a similar experiment and wanted to know if there are certain flags that can be set to do PPO only with 1 or 2 RMs and not all 3,

From reward.py https://github.com/allenai/FineGrainedRLHF/blob/3ce87b80f999f61adfb440df12e14e1771ca4eef/tasks/qa_feedback/training/reward.py#L416, it looks like by-default all reward models have to be present

**Comment by ellenmellon** [comment]
You could set corresponding reward weights to 0 to disable them: https://github.com/allenai/FineGrainedRLHF/blob/3ce87b80f999f61adfb440df12e14e1771ca4eef/tasks/qa_feedback/training/fine_grained_config.yml#L19

**Comment by vishwa27yvs** [comment]
Okay got it, thank you!
