### ISSUE TITLE
training files missing for training finegrained reward models

### ISSUE THREAD

**Issue by wise-east** [allenai/FineGrainedRLHF#3]
Hello, thanks for the great work and making this repo easy to follow and replicate your work. 

In trying to run the commands used for training the reward models from scratch, e.g. `bash tasks/qa_feedback/reward_modeling/train_fact_rm.sh`, I get the error `FileNotFoundError: Unable to find '/home/ec2-user/FineGrainedRLHF/./tasks/qa_feedback/data/F-ERR_sentence/train.json' at /home/ec2-user/FineGrainedRLHF` and indeed the repo doesn't contain these JSON files. 

I think these files are missing and need to be added to the repo. Thank you!

**Comment by ellenmellon** [comment]
Hi, you'll need to run `bash tasks/qa_feedback/reward_modeling/create_rm_train_files.sh` to create reward model training files first.

**Comment by wise-east** [comment]
that worked, thank you! 

FYI the training script asks for a wandb api key, which I think should be made optional.
